FWDS3DCovUtils.onReady(function(){
	var coverflow = new FWDSimple3DCoverflow({
		//required settings
		coverflowHolderDivId:"myDiv",
		coverflowDataListDivId:"coverflowData",
		displayType:"fluidwidth",
		autoScale:"yes",
		coverflowWidth:940,
		coverflowHeight:550,
		//coverflowHeight:580,
		skinPath:"/wp-content/themes/slate-0.1.0_tyrex/load/skin_black",
		
		//main settings
		backgroundColor:"#000000",
		backgroundImagePath:"",
		backgroundRepeat:"repeat-x",
		showDisplay2DAlways:"no",
		coverflowStartPosition:"center",
		coverflowTopology:"dualsided",
		coverflowXRotation:0,
		coverflowYRotation:0,
		numberOfThumbnailsToDisplayLeftAndRight:3,
		infiniteLoop:"yes",
		rightClickContextMenu:"default",
		fluidWidthZIndex:1000,
									
		//thumbnail settings
		thumbnailWidth:1024,
		thumbnailHeight:550,
		thumbnailXOffset3D:20,
//		thumbnailXSpace3D:165,
		thumbnailXSpace3D:145,
		thumbnailZOffset3D:300,
		thumbnailZSpace3D:130,
		thumbnailYAngle3D:-40,
		thumbnailXOffset2D:20,
		thumbnailXSpace2D:30,
		thumbnailHoverOffset:100,
		thumbnailBorderSize:0,
		thumbnailBackgroundColor:"#FFFFFF",
		thumbnailBorderColor1:"#FFFFFF",
		thumbnailBorderColor2:"#FFFFFF",
		transparentImages:"no",
		thumbnailsAlignment:"center",
		maxNumberOfThumbnailsOnMobile:13,
		showThumbnailsGradient:"no",
		thumbnailGradientColor1:"rgba(0, 0, 0, 0)",
		thumbnailGradientColor2:"rgba(0, 0, 0, 1)",
		showText:"yes",
		textOffset:-300,
		showThumbnailBoxShadow:"yes",
		thumbnailBoxShadowCss:"0px 2px 2px #111111",
		showTooltip:"no",
		dynamicTooltip:"yes",
		showReflection:"yes",
		reflectionHeight:60, 
		reflectionDistance:0,
		reflectionOpacity:.4, 
									
		//controls settings
		slideshowDelay:8000,
		autoplay:"yes",
		disableNextAndPrevButtonsOnMobile:"no",
		controlsMaxWidth:700,
		slideshowTimerColor:"#FFFFFF",
		controlsPosition:"bottom",
		controlsOffset:15,
		showPrevButton:"no",
		showNextButton:"no",
		showSlideshowButton:"no",
		showScrollbar:"no",
		disableScrollbarOnMobile:"yes",
		enableMouseWheelScroll:"no",
		scrollbarHandlerWidth:200,
		scrollbarTextColorNormal:"#000000",
		scrollbarTextColorSelected:"#FFFFFF",
		addKeyboardSupport:"yes",
									
		//categories settings
		showCategoriesMenu:"yes",
		startAtCategory:1,
		categoriesMenuMaxWidth:700,
		categoriesMenuOffset:25,
		categoryColorNormal:"#999999",
		categoryColorSelected:"#FFFFFF",
									
		//lightbox settings
		addLightBoxKeyboardSupport:"yes",
		showLightBoxNextAndPrevButtons:"yes",
		showLightBoxZoomButton:"yes",
		showLightBoxInfoButton:"yes",
		showLightBoxSlideShowButton:"yes",
		showLightBoxInfoWindowByDefault:"no",
		slideShowAutoPlay:"no",
		lightBoxVideoAutoPlay:"no",
		lightBoxVideoWidth:640,
		lightBoxVideoHeight:480,
		lightBoxIframeWidth:800,
		lightBoxIframeHeight:600,
		lightBoxBackgroundColor:"#000000",
		lightBoxInfoWindowBackgroundColor:"#FFFFFF",
		lightBoxItemBorderColor1:"#fcfdfd",
		lightBoxItemBorderColor2:"#e4FFe4",
		lightBoxItemBackgroundColor:"#333333",
		lightBoxMainBackgroundOpacity:.8,
		lightBoxInfoWindowBackgroundOpacity:.9,
		lightBoxBorderSize:0,
		lightBoxBorderRadius:0,
		lightBoxSlideShowDelay:4000
	});
});

